"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Application_1 = require("./Application");
var saber_ioc_1 = require("saber-ioc");
var saber_dom_1 = require("saber-dom");
var Layout_1 = require("./injectable/Layout");
var Factory_1 = require("./injectable/Factory");
var Matrix_1 = require("./singletons/Matrix");
var Canvas_1 = require("./singletons/Canvas");
var Block_1 = require("./injectable/Block");
saber_ioc_1.Injectable()(saber_dom_1.TouchFront);
new saber_ioc_1.SaIOC.Container(Application_1.Application, Layout_1.Layout, Factory_1.Factory, Matrix_1.Matrix, saber_dom_1.TouchFront, Canvas_1.Canvas, Block_1.Block).run();
