"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Application_1 = require("./Application");
var saber_ioc_1 = require("saber-ioc");
var Layout_1 = require("./injectable/Layout");
var Factory_1 = require("./injectable/Factory");
var Matrix_1 = require("./singletons/Matrix");
var TouchFront_1 = require("./injectable/TouchFront");
var Canvas_1 = require("./singletons/Canvas");
var Block_1 = require("./injectable/Block");
new saber_ioc_1.SaIOC.Container(Layout_1.Layout, Factory_1.Factory, Application_1.Application, Matrix_1.Matrix, TouchFront_1.TouchFront, Canvas_1.Canvas, Block_1.Block).run();
